//
// Created by glumes on 2019/3/25.
//

#ifndef VULKAN_TUTORIAL_RENDERPASS_AND_FRAMEBUFFER_H
#define VULKAN_TUTORIAL_RENDERPASS_AND_FRAMEBUFFER_H


class renderpass_and_framebuffer {

};


#endif //VULKAN_TUTORIAL_RENDERPASS_AND_FRAMEBUFFER_H
